import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const write=(name,value)=>fs.writeFileSync(path.join(root,name),value);
const attributes=['Сила','Выносливость','Ловкость','Восприятие','Интеллект','Мудрость','Инициатива','Удача','Вера','Харизма'];
// Только сведения для игроков; данные мастерского сайта сюда не импортируются.
const people=[
 {id:'neko',title:'Неко',subtitle:'Длинный лук',sex:'Женский',move:10,vision:10,stats:[1,1,2,1,2,1,1,1,0,1],weapon:'Длинный лук из дуба',damage:'2–3',range:'16 клеток',category:'Луки',specific:'Длинный лук',note:'Железная стрела: 1–2 урона. Лук добавляет 1.',abilities:[['Точный выстрел','Урон ×1,5','Дробный урон округляется вверх.'],['Дальний выстрел','Дальность ×2','16 → 32 клетки. Можно совместить с точным выстрелом.']]},
 {id:'human',title:'Человек',subtitle:'Глефа',sex:'Мужской',move:5,vision:1,stats:[1,1,1,1,1,1,1,1,2,1],weapon:'Глефа из железа',damage:'1–3',range:'Ближний бой',category:'Древковое оружие',specific:'Глефа',note:'Урон при силе 1. При попадании результат определяет мастер.',abilities:[['Критический удар','Урон ×1,5','Дробный урон округляется вверх.'],['Оглушающий удар','Оглушение · 2 раунда','Полностью лишает цель действий при успешном оглушении. Сопротивление цели учитывает мастер.']]}
];
const icon="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect x='5' y='3' width='22' height='26' rx='3' fill='%231c2829' stroke='%23d3ac69' stroke-width='2'/%3E%3Cpath d='M10 11h12M10 16h12M10 21h8' stroke='%23d3ac69' stroke-width='2'/%3E%3C/svg%3E";
const shell=(title,content,cls='')=>`<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#10181c"><meta name="description" content="Карточка игрока: характеристики, здоровье, снаряжение и изученные способности."><title>${title} · Карточки</title><link rel="icon" href="${icon}"><link rel="stylesheet" href="styles.css">${cls?'<script src="card-state.js" defer></script><script src="card.js" defer></script>':''}</head><body class="${cls}" data-character="${cls}"><a class="skip" href="#main">К карточке</a><div class="frame"><header class="topbar"><a href="index.html">ВЕЛИКАЯ ИМПЕРИЯ</a><span>КАРТОЧКИ ИГРОКОВ</span></header><main id="main">${content}</main><footer>Карточки игроков · ХП и инвентарь сохраняются на этом устройстве</footer></div></body></html>`;
for(const p of people){
const h=`<a class="back" href="index.html">← Все карточки</a><header class="hero"><p class="eyebrow">ПЕРСОНАЖ · ИМЕНИ ПОКА НЕТ</p><h1>${p.title}</h1><p class="subtitle">${p.subtitle} <span>·</span> Пол: ${p.sex.toLowerCase()}</p></header>
<div class="overview"><section class="health"><span class="label">ХИТ-ПОИНТЫ</span><strong aria-live="polite"><span id="hp-value">5</span> <small>/ <span id="hp-max">5</span></small></strong><meter id="hp-meter" min="0" max="5" value="5" aria-label="ХП: 5 из 5"></meter><div class="counter-controls"><button type="button" id="hp-minus" aria-label="Убавить 1 ХП">−1 ХП</button><button type="button" id="hp-plus" aria-label="Прибавить 1 ХП" disabled>+1 ХП</button></div><p id="hp-status" class="hint" role="status"></p><span class="hint" id="hp-formula">3 базовых + 2 от выносливости</span></section><section class="armor"><span class="label">БРОНЯ</span><h2 id="armor-name">Туника</h2><p id="armor-note">Без бонусов к ХП.</p><button type="button" id="edit-armor" aria-expanded="false" aria-controls="armor-form">Изменить броню</button><form id="armor-form" class="gear-form" hidden><label>Название<input id="armor-input" maxlength="120" required></label><label>Бонус к ХП<input id="armor-hp" type="number" min="0" max="999" step="1" required></label><button type="submit">Сохранить броню</button></form></section></div>
<div class="quick-stats"><div><strong data-movement>${p.move}</strong><span>клеток за ход</span></div><div><strong>${p.vision} м</strong><span>ночное зрение</span></div><div><strong id="initiative-value">1</strong><span>инициатива</span></div><div><strong>1:3</strong><span>перестат</span></div></div>
<section class="section"><h2>Характеристики</h2><dl class="attributes">${attributes.map((a,i)=>`<div><dt>${a}</dt><dd data-stat="${i}">${p.stats[i]}</dd></div>`).join('')}</dl><p class="hint"><span id="stats-note">Бонусов от предметов нет.</span></p></section>
<section class="section"><h2>Оружие</h2><article class="weapon"><div><p class="eyebrow">ОРУЖИЕ</p><h3 id="weapon-name">${p.weapon}</h3><p id="weapon-range">${p.range}</p></div><div class="damage"><strong id="weapon-damage">${p.damage}</strong><span>урона</span></div></article><p class="hint">Урон и свойства оружия определяет мастер.</p><button type="button" id="edit-weapon" aria-expanded="false" aria-controls="weapon-form">Изменить оружие</button><form id="weapon-form" class="gear-form" hidden><label>Название<input id="weapon-input" maxlength="120" required></label><label>Урон<input id="damage-input" maxlength="50" required placeholder="Например, 2–3"></label><label>Дальность / тип боя<input id="range-input" maxlength="80" required></label><fieldset><legend>Бонусы оружия к характеристикам</legend><div class="bonus-inputs"><label>Сила<input id="bonus-0" type="number" min="0" max="999" step="1" value="0" required></label><label>Выносливость<input id="bonus-1" type="number" min="0" max="999" step="1" value="0" required></label><label>Ловкость<input id="bonus-2" type="number" min="0" max="999" step="1" value="0" required></label><label>Восприятие<input id="bonus-3" type="number" min="0" max="999" step="1" value="0" required></label><label>Интеллект<input id="bonus-4" type="number" min="0" max="999" step="1" value="0" required></label><label>Мудрость<input id="bonus-5" type="number" min="0" max="999" step="1" value="0" required></label><label>Инициатива<input id="bonus-6" type="number" min="0" max="999" step="1" value="0" required></label><label>Удача<input id="bonus-7" type="number" min="0" max="999" step="1" value="0" required></label><label>Вера<input id="bonus-8" type="number" min="0" max="999" step="1" value="0" required></label><label>Харизма<input id="bonus-9" type="number" min="0" max="999" step="1" value="0" required></label></div></fieldset><button type="submit">Сохранить оружие</button></form><p class="hint">Введи бонусы 0, +1, +2 или другие значения от мастера. Характеристики пересчитываются; владения и способности автоматически не меняются. Список инвентаря ведётся отдельно.</p><div class="mastery"><p><span>${p.category}</span><strong>1 уровень</strong></p><p><span>${p.specific}</span><strong>1 уровень</strong></p></div></section>
<section class="section"><h2>Способности</h2><p class="hint">Боевые способности пока не изучены. Владения категорией и конкретным оружием указаны выше.</p></section>
${p.id==='human'?'<section class="section"><h2>Покровитель</h2><p><strong>Бешаба</strong> — богиня неудачи. Вера: <span id="faith-value">2</span>.</p><p class="hint">Сейчас бонусов за поклонение нет.</p></section>':''}
<section class="section"><h2>Монеты</h2><p class="coin-total"><output id="coins-value" aria-live="polite">0</output> <span>монет</span></p><div class="coin-controls"><label for="coin-amount">Сумма<input type="number" id="coin-amount" min="1" max="999999999" step="1" value="1" inputmode="numeric"></label><button type="button" id="coins-minus" disabled>− Монеты</button><button type="button" id="coins-plus">+ Монеты</button></div><p class="hint">Начальная сумма пока не указана: внеси монеты, полученные от мастера.</p></section>
<section class="section"><h2>Инвентарь</h2><ul id="inventory-list" class="inventory-list"></ul><p id="inventory-empty" class="hint" hidden>Инвентарь пуст.</p><form id="item-form" class="item-form"><label for="item-name">Предмет<input id="item-name" name="item" maxlength="120" required placeholder="Например, железные стрелы"></label><label for="item-quantity">Количество<input type="number" id="item-quantity" name="quantity" min="1" max="9999" step="1" value="1" inputmode="numeric" required></label><button type="submit">Добавить вещь</button></form><p class="hint">Список вещей не меняет характеристики и надетое снаряжение автоматически.</p><p id="save-status" class="hint" role="status">ХП, монеты и вещи сохраняются в этом браузере отдельно для каждого персонажа. Между устройствами синхронизации нет.</p><p id="action-status" class="hint" role="status"></p><noscript><p>Для изменения ХП, монет и инвентаря включи JavaScript.</p></noscript></section>
<section class="section reminder"><h2>Памятка на ход</h2><ul><li>Если пройдёшь меньше <span data-movement>${p.move}</span> клеток, можешь затем атаковать или достать предмет. После этого ход заканчивается.</li><li>Обычно доступна одна атака за ход.</li><li>При 0 ХП теряешь сознание. На спасение есть 5 раундов.</li></ul></section>`;
write(p.id+'.html',shell(p.title,h,p.id));
}
write('index.html',shell('Персонажи',`<header class="hero"><p class="eyebrow">НАЧАЛО ПРИКЛЮЧЕНИЯ</p><h1>Твой персонаж</h1><p class="subtitle">Характеристики, снаряжение и способности.</p></header><div class="selection">${people.map(p=>`<a href="${p.id}.html" class="select-card ${p.id}"><span class="eyebrow">${p.subtitle}</span><h2>${p.title}</h2><p>5 ХП · ${p.move} клеток за ход</p><span class="open">Открыть карточку →</span></a>`).join('')}</div>`));
console.log('Built 2 player cards and index.');
